server:
  servlet:
    context-path: /notifications
  port: 8084

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  datasource:
    url: jdbc:postgresql://localhost:5435/notification_db
    username: postgres
    password: changeme

  jpa:
    hibernate:
      ddl-auto: update

  kafka:
    bootstrap-servers: localhost:19092
    consumer:
      group-id: ${spring.application.name}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring.json.trusted.packages: com.linkedin.*
        spring.json.use.type.headers: false
