server:
  servlet:
    context-path: /posts
  port: 8081
  
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/post_db
    username: postgres
    password: changeme

  jpa:
    hibernate:
      ddl-auto: update
